[tool.towncrier]
# Read https://github.com/ethereum/trinity/newsfragments/README.md for instructions
package = "trinity"
filename = "docs/release_notes.rst"
directory = "newsfragments"
underlines = ["-", "~", "^"]
issue_format = "`#{issue} <https://github.com/ethereum/trinity/issues/{issue}>`__"
